version: '3.8'
services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "9000:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: